export const Buttons = {
  ButtonX: require('../images/Buttons/ButtonX.png'),
  ButtonSpeaker: require('../images/Buttons/ButtonSpeaker.png'),
  ButtonThunder: require('../images/Buttons/ButtonThunder.png'),
  ButtonHamburgerMenu: require('../images/Buttons/ButtonHamburgerMenu.png'),
};

export const ShoutFrames = [
  require('../images/Shouts/Tabeli_Export_0000_Frame.png'),
  require('../images/Shouts/Tabeli_Export_0001_Music.png'),
  require('../images/Shouts/Tabeli_Export_0002_Candy.png'),
  require('../images/Shouts/Tabeli_Export_0003_IngAndYang.png'),
  require('../images/Shouts/Tabeli_Export_0004_Colorful.png'),
  require('../images/Shouts/Tabeli_Export_0005_CyberPunk.png'),
  require('../images/Shouts/Tabeli_Export_0006_Art.png'),
  require('../images/Shouts/Tabeli_Export_0007_Graphite.png'),
  require('../images/Shouts/Tabeli_Export_0008_Vitrage.png'),
  require('../images/Shouts/Tabeli_Export_0009_Default.png'),
  require('../images/Shouts/Tabeli_Export_0010_LARP.png'),
  require('../images/Shouts/Tabeli_Export_0011_BoardGames.png'),
  require('../images/Shouts/Tabeli_Export_0012_MOHITO-ON-THE-BEACH.png'),
  require('../images/Shouts/Tabeli_Export_0013_Theatre.png'),
  require('../images/Shouts/Tabeli_Export_0014_Movie-Night.png'),
  require('../images/Shouts/Tabeli_Export_0015_Coffee-Time.png'),
  require('../images/Shouts/Tabeli_Export_0016_Pizza.png'),
  require('../images/Shouts/Tabeli_Export_0017_Pancakes.png'),
  require('../images/Shouts/Tabeli_Export_0018_Sushi.png'),
  require('../images/Shouts/Tabeli_Export_0019_Helloween.png'),
  require('../images/Shouts/Tabeli_Export_0020_Flowers.png'),
  require('../images/Shouts/Tabeli_Export_0021_Romance.png'),
  require('../images/Shouts/Tabeli_Export_0022_Poker-Night.png'),
  require('../images/Shouts/Tabeli_Export_0023_Balloons.png'),
  require('../images/Shouts/Tabeli_Export_0024_Disco.png'),
  require('../images/Shouts/Tabeli_Export_0025_Girl-Party.png'),
  require('../images/Shouts/Tabeli_Export_0026_Love.png'),
  require('../images/Shouts/Tabeli_Export_0027_Bones.png'),
  require('../images/Shouts/Tabeli_Export_0028_Sport.png'),
  require('../images/Shouts/Tabeli_Export_0029_Beer.png'),
];
